# Reusable operation parameters

ItemIdParam:
  name: itemId
  in: path
  required: true
  description: The unique identifier (UUID) of the item.
  schema:
    type: string
    format: uuid

LimitParam:
  name: limit
  in: query
  required: false
  description: Maximum number of items to return.
  schema:
    type: integer
    format: int32
    default: 20
    minimum: 1
    maximum: 100

OffsetParam:
  name: offset
  in: query
  required: false
  description: Number of items to skip for pagination.
  schema:
    type: integer
    format: int32
    default: 0
    minimum: 0

CorrelationIdHeader:
  name: X-Correlation-ID
  in: header
  required: false
  description: Optional request correlation ID for tracing.
  schema:
    type: string
    format: uuid
